### ISSUE TITLE
Possibility to change fan icon

### ISSUE THREAD

**Issue by nac6** [brian-su/homebridge-sonos-so-simple#14]
I find the fan icon not suitable for volume as its animated.

Is it possible to to change the fan icon to something a bit more volume like.

Thanks.

**Comment by brian-su** [comment]
Hi! Sorry for the delay. Not really, the fan icon is a HomeKit icon. Due to the way HomeKit works the plugin broadcasts the speaker as either a fan or a lightbulb in order to make the volume accessible as a %age. It's a quirky way to do it but the speaker type in HomeKit doesn't work for reasons I can no longer remember. Apologies!
